### PR TITLE
perf(typing): improve performance of PropsOf

### PR DESCRIPTION
**Pull request by mskelton**
First of all, thank you for the work you put into this library as it makes creating polymorphic components so easy!  The only pain point I've had with this library is that the performance of type checking takes a fairly significant hit compared to standard type checking.  After a lot of digging and looking at what other component libraries are doing to solve this problem, I found the approach that Chakra UI took in https://github.com/chakra-ui/chakra-ui/pull/1627 made a significant impact on performance by not using `JSX.IntrinsicElements` when typing the as prop and instead using `string`.  Through the use of conditional types, it can still maintain the same strong typing.

The following screenshot shows the delay in type checking with the existing approach and then the improved speed with the new approach in this PR.

perf

This is my test cases to ensure the type checking is working properly.

Screen Shot 2020-10-01 at 1 32 18 PM

### CODE REVIEW

**Comment by kripod** [comment]
Thank you for this very valuable PR! I've checked the latest type definitions of React and found the following:

```ts
type ComponentProps<T extends keyof JSX.IntrinsicElements | JSXElementConstructor<any>> =
    T extends JSXElementConstructor<infer P>
        ? P
        : T extends keyof JSX.IntrinsicElements
            ? JSX.IntrinsicElements[T]
            : {};
```

It seems to be even more performant than your proposed approach. You've made a really great point and opened my eye about this issue, thank you!

**Comment by kripod** [comment]
This has just been resolved with dd6713153f8eb28374f7c71c8c6e166c8780ee9d.

**Comment by mskelton** [comment]
Just took a look at the latest changes and it looks like `ComponentPropsWithRef` is significantly slower than `ComponentProps` but it looks like you used `ComponentPropsWithRef` in your commit.  Any reason why?

**Comment by kripod** [comment]
I used that as it was recommended by the comments. However, please feel free to open a PR, changing it to `ComponentProps`.

**Pull request closed without merging**
